# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, default='Europe/London', max_length=50)),
                ('formatdate', models.CharField(blank=True, choices=[('DD-MM-YYYY', 'DD-MM-YYYY'), ('MM-DD-YYYY', 'MM-DD-YYYY')], default='DD-MM-YYYY', max_length=20)),
                ('firstdayweek', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='MALE', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('color_project', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('repeating', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2017, 9, 22, 7, 40, 1, 911791, tzinfo=utc), null=True)),
                ('time', models.TimeField(blank=True, default=datetime.datetime(2017, 9, 22, 7, 40, 1, 911791, tzinfo=utc), null=True)),
                ('date_finish', models.DateField(blank=True, default=datetime.datetime(2017, 9, 22, 7, 40, 1, 911791, tzinfo=utc), null=True)),
                ('active', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='JtdiTASKS.Project')),
            ],
        ),
    ]
