# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0002_task_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planed_date_finish',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Приоритет 1'), ('2', 'Приоритет 2'), ('3', 'Приоритет 3'), ('4', 'Приоритет 4')], default='4', max_length=20),
        ),
    ]
