# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0003_auto_20171018_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksTimeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('finish', models.DateTimeField(blank=True, default=None, null=True)),
                ('full_time', models.FloatField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JtdiTASKS.Task')),
            ],
        ),
    ]
