# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0003_auto_20170930_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('red', 'Степень важности 1'), ('yellow', 'Степень важности 2'), ('green', 'Степень важности 3'), ('grey', 'Степень важности 4')], default='grey', max_length=20),
        ),
    ]
