# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0004_auto_20171002_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind',
            field=models.BooleanField(default=True),
        ),
    ]
