# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JtdiTASKS', '0005_task_remind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_invite', models.CharField(max_length=200)),
                ('invited', models.BooleanField(default=False)),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='partnergroup',
            name='task',
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JtdiTASKS.Project'),
        ),
    ]
