# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0005_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
