# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0006_auto_20171002_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='grey', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Степень важности 1'), ('2', 'Степень важности 2'), ('3', 'Степень важности 3'), ('4', 'Степень важности 4')], default='4', max_length=20),
        ),
    ]
