# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0007_commentstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='firstdayweek',
            field=models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='Europe/Moscow', max_length=50),
        ),
    ]
