# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0007_auto_20171003_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
