# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0008_auto_20171024_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_notify',
            field=models.BooleanField(default=True),
        ),
    ]
