# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0008_auto_20171004_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
