# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0009_project_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
