# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0010_auto_20171103_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day_week',
            field=models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=20, null=True),
        ),
    ]
