# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0010_auto_20171006_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='not_invited',
            field=models.BooleanField(default=False),
        ),
    ]
