# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('JtdiTASKS', '0011_auto_20171110_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('new', models.BooleanField(default=True)),
                ('event', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
