# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0011_inviteuser_not_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='user_invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
