# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0012_auto_20171010_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
