# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0013_auto_20171114_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtable',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='JtdiTASKS.Project'),
        ),
    ]
