# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JtdiTASKS', '0016_queuetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuetask',
            old_name='remind',
            new_name='reminded',
        ),
    ]
